### PR TITLE
Add typed comments

### PR DESCRIPTION
**Pull request by skorokithakis**
I have added typed comments. Comments that start with `#dilc:` will get typed out as normal:

```
#dilc: This comment will get typed to the console with the `dilc:` part removed.
```

### CODE REVIEW

**Comment by skorokithakis** [comment]
I have tested this and it works well.

**Comment by sloria** [comment]
Is your use case met by the existing `#doitlive commentecho: true` feature?

**Comment by skorokithakis** [comment]
Not really, because those comments are echoed instead of typed out by the keyboard. I would like the comments to be typed out, like other code.

**Comment by sloria** [comment]
What do you think about

```
#doitlive comment: This comment will get typed to the console with the `doitlive comment:` part removed.
```

for consistency with the existing syntax?

**Comment by skorokithakis** [comment]
Sure, that looks good. I'll change it when I get home.

**Comment by sloria** [comment]
Actually, maybe it'd be nicer to use the existing `#doitlive commentecho`. Something like

```
#doitlive commentecho: type

# This comment will get magictyped
```

wdyt?

**Comment by skorokithakis** [comment]
Hmm, won't that confuse things two much? People might conflate the echoed and the typed comments.

**Comment by sloria** [comment]
That's true, but `#doitlive commentecho: type` signals its intention better than `#doitlive comment: ...`, I think, and it makes echo'd comments and typed comments mutually exclusive, which seems desirable.

That said, I don't have strong feelings about it. Since you're the one that is using this feature, I'll defer to you to decide which is better.

**Comment by skorokithakis** [comment]
Oh sorry, you meant "type" as in, the literal `type`? I thought you meant something like `# doitlive commentecho: This is my comment`, which would be confusing.

That seems best, but it would require rewriting pretty much the entire PR, as far as I can see. I will look into that and get back to you.

**Comment by sloria** [comment]
closing this for now. feel free to pick this back up from where we left off

**Pull request closed without merging**
